CREATE SEQUENCE SEQ_ADDRESS_ID START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE SEQ_USER_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE TBL_ADDRESS (ADDRESS_ID BIGINT NOT NULL, CODE_POSTAL VARCHAR(255) NOT NULL, COMPLEMENT_ADDR VARCHAR(255), NO_ET_VOIE VARCHAR(255) NOT NULL, VILLE VARCHAR(255) NOT NULL, USER_ADDRESSES BIGINT, PRIMARY KEY (ADDRESS_ID));
CREATE TABLE TBL_USER (USER_ID BIGINT NOT NULL, USER_AVATAR BLOB, USER_EMAIL VARCHAR(255), USER_NAME VARCHAR(255) NOT NULL, PRIMARY KEY (USER_ID));
